#!/bin/bash
help='create <project_name> [-t <package_type>]'

project_name='my_app'
package_type='jar'

## check input args
parseArgs() {
    case $# in
        3) # specified project name and package type
            if [ $2 = '-t' ]; then package_type=$3; fi
            if [ $3 != 'jar' -a $3 != 'war' ]; then package_type='jar'; fi
            project_name=$1;;
        1) # specified project name
            project_name=$1;;
        *) # use default project and type of package
            ;;
    esac
}

parseArgs $@

## download template
wget http://192.168.7.244:8080/job/Jcm-Project-Template/ws/dist/Jcm-Project-Template-1.0.tar.gz

if [ ! -f Jcm-Project-Template-1.0.tar.gz ]; then 
    echo 'Error: Download Failed!!!' 
    exit 0
fi

echo '$project_name.tar.gz is downloaded!'
tar -vzxf Jcm-Project-Template-1.0.tar.gz
rm -f Jcm-Project-Template-1.0.tar.gz
mv Jcm-Project-Template-1.0 ${project_name}
echo 'temp file is deleted!'
sed -i "s/name=\"Jcm-Project-Template\"/name=\"${project_name}\"/" ${project_name}/build.xml
sed -i "s/module=\"Jcm-Project-Template\"/module=\"${project_name}\"/" ${project_name}/ivy.xml
echo 'initialized project configure!'
echo ${project_name} is create!


